services:
  accounts:
    image: "denmo530/accounts:0.0.1"
    container_name: accounts-api
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-microservice
  cards:
    image: "denmo530/cards:0.0.1"
    container_name: cards-api
    ports:
      - "8100:8100"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-microservice
  loans:
    image: "denmo530/loans:0.0.1"
    container_name: loans-api
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-microservice

networks:
  bank-microservice:
    driver: "bridge"  