server:
  port: 8090

spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  profiles:
    active: staging
    default: default
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "Bank loans application"
    version: "1.0.0"

