server:
  port: 8071
  jetty:
    max-http-response-header-size: 64KB

spring:
  application:
    name: "bank-config-server"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/denmo530/bank-microservices-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        monitor:
          enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: "guest"
    password: "guest"

encrypt:
  key: "THIS1IS2A3FAKE4KEY5FOR6THIS7LEARNING8PROJECT9"

management:
  endpoints:
    web:
      exposure:
        include: "*"
