build:
  version: "2.0.0"

accounts:
  message: "Welcome to FAKEBANK accounts related local APIs"
  contactDetails:
    name: "John Doe - QA Lead"
    email: "john_QA@doe.com"
  onCallSupport:
    - (555) 555-1234
    - (523) 523-1234
