build:
  version: "3.0.0"

accounts:
  message: "Welcome to FAKEBANK accounts related local APIs"
  contactDetails:
    name: "John Doe - Local Lead"
    email: "john_local@doe.com"
  onCallSupport:
    - (555) 555-1234
    - (523) 523-1234
